Repository Bauddhik-Geeks/Coding, pull requests merged in 2021-10, with the labels that each got.

#38 Added 5 codeforces questions.
  C++/Codeforces/1492_B_Card_Deck.cpp
  C++/Codeforces/1579_B_Shifting Sort.cpp
  C++/Codeforces/227_B_Effective_Approach.cpp
  C++/Codeforces/266_B_Queue_at_the_School.cpp
  C++/Codeforces/320_A_MagicNumbers.cpp
Labels: hacktoberfest-accepted

#31 added leetcode(96) Unique Binary Search Trees
  C++/Data_Structure_And_Algorithms/Arrays/count_primes.cpp
  C++/Data_Structure_And_Algorithms/Arrays/first_missing_positive.cpp
  C++/Data_Structure_And_Algorithms/Arrays/trapping_rain_water.cpp
  C++/Data_Structure_And_Algorithms/Tree/6).unique_bst.cpp
Labels: documentation, Do-Not-Merge, cplusplus

#35 Adding 4 Java Leetcode solutions
  Java/Leetcode/Easy/LongestCommonPrefix.java
  Java/Leetcode/Easy/RemoveDuplicatesFromSortedArray.java
  Java/Leetcode/Easy/ReverseInteger.java
  Java/Leetcode/Easy/RomanToInteger.java
Labels: documentation, java

#37 Added 4 medium and hard level codeforces solutions
  C++/Codeforces/339_D_Xenia and Bit Operations.cpp
  C++/Codeforces/545_C_Woodcutters.cpp
  C++/Codeforces/580_C_Kefa and Park.cpp
  C++/Codeforces/Create 1567_C_Carrying Conundrum.cpp
Labels: documentation, cplusplus, hacktoberfest-accepted

#40 binary search program in python added
  Python/DSA/Graph/kosaraju.py
  Python/DSA/Searching/binarysearch.py
Labels: documentation, python

#36 Added four Medium level leetcode solutions
  C++/Leetcode/Miscellaneous/3Sum.cpp
  C++/Leetcode/Miscellaneous/Letter Combinations of a Phone Number.cpp
  C++/Leetcode/Miscellaneous/rotate-image.cpp
  C++/Leetcode/Miscellaneous/unique-paths.cpp
Labels: documentation, cplusplus

#44 Added 4 problems from Codechef starters 9
  C++/Codechef/Codechef_Starters_9/Black_Cells_in_a_chessboard.cpp
  C++/Codechef/Codechef_Starters_9/Bus_full_of_passengers.cpp
  C++/Codechef/Codechef_Starters_9/Friend_Groups_in_a_Line.cpp
  C++/Codechef/Codechef_Starters_9/Large_Square.cpp
Labels: documentation, enhancement, cplusplus

#33 Add files via upload
  C++/Data_Structure_And_Algorithms/Sorting/bubble_sort.cpp
  C++/Data_Structure_And_Algorithms/Sorting/merge_sort.cpp
  Python/codechef/beginner/Buggy_calc.py
  Python/codechef/beginner/atm.py
  Python/codechef/beginner/avg.py
  Python/codechef/beginner/books.py
  Python/codechef/beginner/covid_run.py
  Python/codechef/beginner/easy.py
  Python/codechef/beginner/sale.py
  Python/codechef/beginner/sequence.py
Labels: documentation, cplusplus, hacktoberfest-accepted

#43 Added Sorting Folder
  C++/Data_Structure_And_Algorithms/Sorting/Bubble_sort.cpp
  C++/Data_Structure_And_Algorithms/Sorting/Insertion_sort.cpp
  C++/Data_Structure_And_Algorithms/Sorting/Selection_sort.cpp
Labels: documentation, cplusplus, hacktoberfest-accepted

#46 Bubble sort added
  C++/Data_Structure_And_Algorithms/Sorting/BubbleSort/BubbleSort.cpp
  C++/Data_Structure_And_Algorithms/Sorting/BubbleSort/Problem1.cpp
  C++/Data_Structure_And_Algorithms/Sorting/BubbleSort/Problem2.cpp
  C++/Data_Structure_And_Algorithms/Sorting/BubbleSort/Problem3.cpp
  C++/Data_Structure_And_Algorithms/Sorting/BubbleSort/Problem4.cpp
Labels: documentation, Do-Not-Merge, cplusplus

#53 Added the solutions of CodeChef Starters_14
  C++/Codechef/CodeChef_Starters_14(Div 3)/Counting_Tuples.cpp
  C++/Codechef/CodeChef_Starters_14(Div 3)/Diagonal_Movement.cpp
  C++/Codechef/CodeChef_Starters_14(Div 3)/Fixed_number_of_Fixed_Points.cpp
  C++/Codechef/CodeChef_Starters_14(Div 3)/Odd_GCD.cpp
  C++/Codechef/CodeChef_Starters_14(Div 3)/RCB_and_Playoffs.cpp
  C++/Codechef/CodeChef_Starters_14(Div 3)/Task_Times.cpp
Labels: documentation, enhancement, cplusplus, hacktoberfest-accepted

#50 Codechef_Starters_14
  C++/Codechef/Codechef_Starters_14/Diagonal_Movement.cpp
  C++/Codechef/Codechef_Starters_14/Fixed_number_of_Fixed_Points.cpp
  C++/Codechef/Codechef_Starters_14/Odd_GCD.cpp
  C++/Codechef/Codechef_Starters_14/RCB_and_Playoffs.cpp
Labels: documentation, enhancement, cplusplus

#52 Added 5 easy leetcode questions in java issue #51
  Java/LeetCode/Easy/Find_N_Unique_Integers_Sum_up_to_Zero.java
  Java/LeetCode/Easy/Lucky_Numbers_in_a_Matrix.java
  Java/LeetCode/Easy/Maximum_subarray.java
  Java/LeetCode/Easy/Reshape_the_matrix.java
  Java/LeetCode/Easy/Transfose_matrix.java
Labels: documentation, enhancement, cplusplus

#28 Added leetcode pow#50 in java
  Java/LeetCode/pow#50.py
Labels: documentation, cplusplus

#60 Added Binary Search
  C++/Data_Structure_And_Algorithms/Searching/Binary_Search.cpp
  C++/Data_Structure_And_Algorithms/Searching/Linear_Search.cpp
  C++/Data_Structure_And_Algorithms/Searching/Ternary_Search.cpp
Labels: documentation, enhancement, cplusplus

#65 Added 8 DP Problems from Leetcode in CPP.
  C++/Data_Structure_And_Algorithms/Sorting/Bubble_sort.cpp
  C++/Leetcode/Dynamic Programming Medium/2_keys_keyboard.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/partition_equal_subset_sum.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/perfect_squares.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/reducing_dishes_withdp.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/reducing_dishes_withoutdp_sol.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/scramble_string_recursive_tle.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/shortest_common_subsequence_hard.cpp.txt
  C++/Leetcode/Dynamic Programming Medium/triangle_table_without_making_it_accepted.cpp.txt
Labels: documentation, enhancement, cplusplus

#70 Added the Singly LinkedList in C language
  C/README.md
  C/Singly_LinkedList.c
Labels: documentation, enhancement

#66 Added 5 problems from Codeforces Round 739(div 3)
  C++/Codeforces/1560_A_Dislike_of_Threes.cpp
  C++/Codeforces/1560_B_Who's_Opposite?.cpp
  C++/Codeforces/1560_C_Infinity_Table.cpp
  C++/Codeforces/1560_D_Make_Power_of_2.cpp
  C++/Codeforces/1560_E_Polycarp_and_String_Transformation.cpp
Labels: documentation, enhancement, cplusplus

#17 feat : Added Js folder
  JavaScript/README.md
  JavaScript/freecodecamp/Basic JavaScript/README.md
  JavaScript/freecodecamp/README.md
Labels: documentation

#64 Create Class vs Instances.py
  Python/hackerrank/Class vs Instances.py
Labels: documentation, python

#59 largest integer element in array
  C++/Data_Structure_And_Algorithms/Arrays/largest integer element in array.cpp
  C++/Data_Structure_And_Algorithms/Sorting/bubble_sort.cpp
Labels: documentation, cplusplus

#57 add jump search for javascript
  .DS_Store
  JavaScript/.DS_Store
  JavaScript/searching/jump-search.js
Labels: documentation

#54 Created breadth_first_search.cpp
  C++/Data_Structure_And_Algorithms/Graphs/bfs.cpp
Labels: documentation

#27 Created 1174_B Ehab Is an Odd Person.cpp
  C++/Codeforces/1174_B. Ehab Is an Odd Person.cpp
Labels: documentation
